name: 🐋 Publish Docker image on Release

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout code
        uses: actions/checkout@v4

      - name: 🖼️ Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: 🐋 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🚪 Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🗃️ Extract Docker image tag from GitHub Release
        id: vars
        run: |
          # Extract the tag name (e.g., 'v1.0.0' from 'refs/tags/v1.0.0')
          RAW_TAG="${GITHUB_REF##*/}"
          # Remove any potential trailing colons or other problematic characters
          CLEAN_TAG=$(echo "$RAW_TAG" | sed 's/:$//' | sed 's/\.$//' | sed 's/\-$//')
          echo "Extracted RAW_TAG: $RAW_TAG"
          echo "Cleaned TAG: $CLEAN_TAG"
          echo "tag=$CLEAN_TAG" >> "$GITHUB_OUTPUT"

      - name: 🐋 Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/go-go-proxy:${{ steps.vars.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/go-go-proxy:latest
